### ISSUE TITLE
capitalized identifiers are usually used for instantiable objects

### ISSUE THREAD

**Issue by brumm** [minternational/RockPaperScissor#1]
https://github.com/minternational/RockPaperScissor/blob/c0e898259db068addab6895db2c2d24b94e9b98e/rock_paper_scissor.js#L1

The naming and capitalization here is unclear. By convention, all variable names in JavaScript are lower case, except for all-caps constants `const SOME_CONSTANT = 1` or objects which you are expected to instantiate `class SomeClass {}`

Also, the naming should reflect what this is and does, for instance `const moveTypes = []` or something like that

**Comment by minternational** [comment]
Thanks for advice.
I named it correct now.
Issue closed.
