### ISSUE TITLE
last line of event handlers is being returned unnecessarily

### ISSUE THREAD

**Issue by brumm** [minternational/RockPaperScissor#2]
https://github.com/minternational/RockPaperScissor/blob/c0e898259db068addab6895db2c2d24b94e9b98e/rock_paper_scissor.js#L22-L29

The return value [is ignored by the browser](https://devdocs.io/dom/eventlistener/handleevent) and makes it unclear for the reader what is supposed to happen here

**Comment by minternational** [comment]
Handled issue.
Deleted return statement.
Issue closed.
