### ISSUE TITLE
template string is not necessary

### ISSUE THREAD

**Issue by brumm** [minternational/RockPaperScissor#3]
https://github.com/minternational/RockPaperScissor/blob/c0e898259db068addab6895db2c2d24b94e9b98e/rock_paper_scissor.js#L20

since this value does not contain any other non-interpolated characters, you can drop the whole part and just assign directly:

```
userChoose.innerHTML = RockPaperScissor[0];
```

**Comment by minternational** [comment]
Deleted template literals.
Issue closed.
